title: chemotools
description: Chemotools integrates chemometrics with sklearn
theme: just-the-docs

markdown: kramdown
kramdown:
  parse_block_html: true


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
