title: CHEMOTOOLS
description: Chemotools integrates chemometrics with sklearn
baseurl: "/test.docs.pages/docs" 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
